#!/bin/sh

CONF="/etc/dnsmasq.conf"
DNS_LINE="log-facility=/dev/null"
grep -qF "$DNS_LINE" "$CONF" || echo "$DNS_LINE" >> "$CONF"

[ ! -f /usr/lib/lua/luci/controller/rpc.lua ] && cat << 'EOF' > /usr/lib/lua/luci/controller/rpc.lua
module("luci.controller.rpc", package.seeall)

function index()
    entry({"rpc", "getTempInfo"}, call("getTempInfo"), nil).leaf = true
end

function getTempInfo()
    local temp = luci.sys.exec("cat /sys/class/thermal/thermal_zone0/temp")
    local value = tonumber(temp) or 0
    value = string.format("%.1f °C", value / 1000)
    luci.http.prepare_content("application/json")
    luci.http.write_json({ tempinfo = value })
end
EOF

chmod +x /etc/init.d/* 2>/dev/null

uci set uhttpd.main.rfc1918_filter='0'
uci commit uhttpd
/etc/init.d/uhttpd restart

uci -q batch <<EOF
add system sysctl
set system.@sysctl[-1].option='net.core.rmem_max'
set system.@sysctl[-1].value='26214400'

add system sysctl
set system.@sysctl[-1].option='net.core.wmem_max'
set system.@sysctl[-1].value='26214400'

add system sysctl
set system.@sysctl[-1].option='net.core.netdev_max_backlog'
set system.@sysctl[-1].value='5000'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_low_latency'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_tw_reuse'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_window_scaling'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_sack'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_timestamps'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.core.default_qdisc'
set system.@sysctl[-1].value='fq'
EOF

uci commit system
/etc/init.d/sysctl restart

for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
  echo performance > "$cpu/cpufreq/scaling_governor" 2>/dev/null
done

echo "AT+CFUN=1" > /dev/ttyUSB3 2>/dev/null

exit 0
