name: Copy files from 24.10-nss to master

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Needed for full branch history and switching

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout source branch (24.10-nss) and copy files
        run: |
          git checkout 24.10-nss
          mkdir -p temp-copy/.github/workflows
          cp .github/workflows/Build.yml temp-copy/.github/workflows/
          cp -r files temp-copy/
          cp AW1000.seed temp-copy/

      - name: Switch to destination branch (master) and apply changes
        run: |
          git checkout master
          cp temp-copy/.github/workflows/Build.yml .github/workflows/
          cp -r temp-copy/files .
          cp temp-copy/AW1000.seed .

      - name: Replace version names inside Build.yml
        run: |
          sed -i 's/24.10-LNSS/24.10-M/g' .github/workflows/Build.yml
          sed -i 's/24.10-nss/master/g' .github/workflows/Build.yml

      - name: Commit and push
        run: |
          git add -f .github/workflows/Build.yml files AW1000.seed
          git commit -m "Sync from 24.10-nss → master: updated Build.yml, files/, AW1000.seed" || echo "No changes to commit"
          git push origin master
